Remove AssertPermissionTrait
flarum/flags pull request #26
Opened 2020-07-19 20:09 UTC by tankerkiller125

Removes AssertPermissionTrait

2020-07-19 20:28 UTC, askvortsov1 requested changes

2020-07-19 20:28 UTC, askvortsov1 commented on src/Command/CreateFlagHandler.php
> +        $actor->can('flag', $post);
This should be $actor->assertCan

2020-07-19 20:28 UTC, askvortsov1 commented on src/Command/DeleteFlagsHandler.php
> +        $actor->can('viewFlags', $post->discussion);
This should be $actor->assertCan

2020-07-19 20:52 UTC, datitisev commented on src/Api/Controller/ListFlagsController.php
> +        ! $actor->isGuest();
This won't do anything?

2020-07-19 22:12 UTC, tankerkiller125 commented on src/Api/Controller/ListFlagsController.php
> +        ! $actor->isGuest();
Fixed in newest commit

2020-07-20 06:01 UTC, franzliedke approved these changes

2020-07-20 06:02 UTC, merged