Don't initialize cache until we receive flags
flarum/flags pull request #31
Opened 2020-10-20 21:03 UTC by askvortsov1

We currently get the unread count for the flags badge in navbar via:

```js
getUnreadCount() {
    return app.flags.cache ? app.flags.cache.length : app.forum.attribute('flagCount');
  }
```

But since `app.flags.cache` is initialized to `[]`, this means the count is displayed as `0` until data is loaded in (by clicking on the badge).

If we don't initialize `app.flags.cache` until results are received from API, the code works as expected.

2020-10-20 21:08 UTC, tankerkiller125 approved these changes

2020-10-20 21:10 UTC, askvortsov1 commented
Alternatively, we could check for the length of `app.flags.cache`, but that would return a positive value if all flags have been cleared and `app.flags.cache` is now empty.

2020-10-21 01:40 UTC, clarkwinkelmann requested changes
When I try this PR, I get `TypeError: flags is undefined` in

https://github.com/flarum/flags/blob/4822f7b612f845f552b54202cd7a06f84048d603/js/src/forum/components/FlagList.js#L25

I think the approach looks good overall, maybe we should just change `FlagList` to use `|| []` when retrieving the flags, like we did in beta 13:

https://github.com/flarum/flags/blob/dfa0b09545937b95010f63a122cdc16f9f23696c/js/src/forum/components/FlagList.js#L19

(currently we are missing that conditional)

https://github.com/flarum/flags/blob/4822f7b612f845f552b54202cd7a06f84048d603/js/src/forum/components/FlagList.js#L16

2020-10-24 05:10 UTC, clarkwinkelmann approved these changes
Tested locally. Looks good!

2020-10-25 05:31 UTC, merged